{% set name = "isbnlib" %}
{% set version = "3.10.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/isbnlib-{{ version }}.tar.gz
  sha256: 4679341f56a0df91c635e838a222ce7f10755cb5bcc9548e3f7a8aff5674d3d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6

test:
  imports:
    - isbnlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xlcnd/isbnlib
  summary: Extract, clean, transform, hyphenate and metadata for ISBNs (International Standard Book Number).
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE-LGPL-3.0.txt

extra:
  recipe-maintainers:
    - maxb2
